name: normalCheck

# trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    #env:
    #  CURRY_RUN_GOLDEN: true # run golden tests, see the README for more info
    steps:
      - uses: actions/checkout@v4
      - uses: freckle/stack-action@v4
        with:
          stack-arguments: --coverage
      # prepare and upload test coverage report
      - uses: 8c6794b6/hpc-codecov-action@v3
        with:
          target: stack:spec
      - uses: codecov/codecov-action@v3